version: '2'

services:
  user-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: perihelion
      POSTGRES_PASSWORD: password
      POSTGRES_DB: perihelion-user
    volumes:
      - db:/var/lib/postgres/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831
      - 6832:6832
      - 16686:16686
  user-redis:
    image: redis/redis-stack
    ports:
      - 6379:6379

volumes:
  db:
