[package]
name = "user-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
chrono = { version = "0.4.26", features = ["serde"] }
env_logger = "0.10.0"
serde = { version = "1.0.176", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["chrono"] }
sqlx-postgres = "0.7.1"
tracing = { version = "0.1.37", features = ["log"] }
tracing-actix-web = "0.7.5"
uuid = "1.4.1"
